CREATE TABLE tb_reg_medicamentos (
  id_medicamento                        INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  codigo                                VARCHAR (256) NULL,      
  nombre_comercial                      VARCHAR (256) NULL,
  nombre_generico                       VARCHAR (256) NULL,
  laboratorio                           VARCHAR (256) NULL,
  presentacion                          VARCHAR (256) NULL,
  cantidad                              VARCHAR (256) NULL,
  precio_costo_real_caja                VARCHAR (256) NULL,
  precio_costo_real_unitario            VARCHAR (256) NULL,
  precio_costo_venta_caja               VARCHAR (256) NULL,
  precio_costo_venta_unitario           VARCHAR (256) NULL,
  accion_para_que_sirve                 VARCHAR (256) NULL,
  fecha_de_entrega_medicamento          VARCHAR (256) NULL,
  fecha_de_vencimiento                  VARCHAR (256) NULL,
  stock_maximo_cajas                    VARCHAR (256) NULL,
  stock_maximo_unidad                   VARCHAR (256) NULL,
  stock_minimo_cajas                    VARCHAR (256) NULL,
  stock_minimo_unidad                   VARCHAR (256) NULL,
  extra1              VARCHAR (256) NULL,
  extra2              VARCHAR (256) NULL,
  extra3              VARCHAR (256) NULL,
  user_creacion       VARCHAR (256) NULL,
  user_actualizacion  VARCHAR (256) NULL,
  user_eliminacion    VARCHAR (256) NULL,
  fyh_creacion        DATETIME NULL,
  fyh_actualizacion   DATETIME NULL,
  fyh_eliminacion     DATETIME NULL,
  estado              VARCHAR (11) NULL
);